<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Holiday;

/**
 * HolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $year
     *
     * @return mixed
     */
    public function getAvalaibleFromYear($year)
    {
        $query = 'SELECT d FROM AppBundle:Holiday d WHERE YEAR(d.date) = :year';
        $list = $this->_em->createQuery($query)
        ->execute(array('year'=>$year));

        return $list;
    }
    
}
