<?php

namespace AppBundle\Repository;

/**
 * HolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvalaibleFromYear($year)
    {
        $query = 'SELECT d FROM AppBundle:Holiday d WHERE d.year = :year';
        $list = $this->_em->createQuery($query)
        ->execute(array('year'=>$year));

        return $list;
    }
}
