<?php

namespace AppBundle\Repository;

/**
 * HolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $year
     *
     * @return mixed
     */
    public function getAvalaibleFromYear($year)
    {
        $query = 'SELECT d FROM AppBundle:Holiday d WHERE d.year = :year';
        $list = $this->_em->createQuery($query)
        ->execute(array('year'=>$year));

        return $list;
    }

    /**
     * @param int $year
     *
     * @return array
     */
    public function getArrayAvailableHolidays($year)
    {
        $holidays = array();
        $list       = $this->getAvalaibleFromYear($year);
        foreach ($list as $lst) {
            $date = sprintf('%d-%d-%d', $lst->getYear(), $lst->getMonth(), $lst->getDay());
            $date = new \DateTime($date);
            array_push($holidays, $date->format('Y-m-d'));
        }

        return $holidays;
    }
}
