<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Employee;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function getValidator()
    {
        $req = '';
    }
}
