<?php

namespace AppBundle\Repository;

/**
 * TeamWorkflowModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamWorkflowModelRepository extends \Doctrine\ORM\EntityRepository
{
}
