<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Status;
use AppBundle\Entity\User;
use AppBundle\Entity\VacationRequest;

/**
 * VacationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacationRequestRepository extends \Doctrine\ORM\EntityRepository
{
    public function listNotValidateBy(User $validator)
    {
//        $query = "SELECT * FROM vacation_request v
//                            INNER JOIN employee e ON e.id = v.employee_id
//                            INNER JOIN team t ON t.id = e.team_id
//                            INNER JOIN team_manager tm on t.id = tm.team_id
//                            INNER JOIN `user` u ON tm.validator_id = u.id
//                            WHERE u.id = :uid AND v.status = :status AND v.id NOT IN (
//                              SELECT vs.vacation_id FROM vacation_validation vs WHERE vs.manager_id = :uid
//                            )";

        $query = "SELECT v, e, t, u FROM AppBundle:VacationRequest v 
                          JOIN v.employee e 
                          JOIN e.team t
                          JOIN t.validator u
                          WHERE u.validator = :uid AND v.status = :status AND v.id NOT IN (
                            SELECT vc.id FROM AppBundle:VacationValidation vs JOIN vs.vacation vc WHERE vs.manager = :uid
                          ) ";

        $list = $this->_em->createQuery($query)
                  ->setParameters(['uid' => $validator->getId(), 'status' => VacationRequest::PENDING_STATUS])
                  ->getResult();
        return $list;
    }

    public function history($criteria)
    {
        return $this->_em->getRepository('AppBundle:VacationRequest')->findBy($criteria);
    }
}
