<?php

namespace AppBundle\Repository;

/**
 * ValidatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidatorRepository extends \Doctrine\ORM\EntityRepository
{
}
