<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Employee;

/**
 * ValidatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidatorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByEmployee(Employee $employee)
    {
        return $this->_em->createQuery('
            SELECT e, u FROM AppBundle:Employee e 
            JOIN e.team t
            JOIN AppBundle:TeamValidator v
            JOIN e.user u
            WHERE e.id = :id
        ')->setParameters(array('id'=>$employee->getId()));
    }
}
