<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Employee;

/**
 * ValidatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidatorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByEmployee(Employee $employee)
    {
        return $this->_em->createQuery('
            SELECT u, t, e, tm FROM AppBundle:TeamValidator tm JOIN tm.validator u JOIN tm.team t JOIN t.employee e WHERE e.id = :id')
                ->setParameters(array('id'=>$employee->getId()))->getResult();
        
    }
}
