<?php

namespace AppBundle\Repository;

/**
 * WorkflowModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowModelRepository extends \Doctrine\ORM\EntityRepository
{
}
