<?php

namespace AppBundle\Repository;

/**
 * WorkflowStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
