<?php

namespace AppBundle\Repository;

/**
 * WorkflowStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowStatusRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $params
     *
     * @return array
     */
    public function getStatusBy($params=array())
    {
        $query = 'SELECT wf_mt, s, st FROM AppBundle:WorkflowModelStep wf_mt 
                           JOIN wf_mt.wfStatus s
                           JOIN wf_mt.wfStep st
                           JOIN wf_mt.validator u ';
        if(count($params) > 0) {
            $conditions = array();
            if(array_key_exists('userid',$params)){
                $conditions[] = 'u.id = :userid';
            }
            if(array_key_exists('modelid',$params)){
                $conditions[] = 'wf_mt.wfModel = :modelid';
            }
            if(array_key_exists('team', $params)){
                $query .= 'JOIN AppBundle:TeamWorkflowModel tm';
                $conditions[] = 'tm.team = :team';
            }
            if (count($conditions) > 0){
                $query .= ' WHERE '. implode(' AND ', $conditions);
            }
        }

        return $this->_em->createQuery($query)->setParameters($params)->getResult();
    }
}
