# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #Application's internal services
    app.vacation_request_manager:
        class: 'AppBundle\Manager\VacationRequestManager'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
    app.wf_step_manager:
        class: 'AppBundle\Manager\WorkflowStepManager'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
    app.holiday_manager:
        class: 'AppBundle\Manager\HolidayManager'
        arguments:
            - "@doctrine.orm.entity_manager"
    #Application's Event Listeners
    app.event.listeners:
        class: 'AppBundle\Listener\VacationListener'
        tags:
            - { name: "kernel.event_listener", event: "app.on_validate_event", method: "onValidate" }
            - { name: "kernel.event_listener", event: "app.on_submit_vacation_event", method: 'onSubmitRequest'}
    #Application's external services