# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.mailer_manager:
        class: 'AppBundle\Manager\MailerManager'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@mailer"
            - "@templating"
            - "@translator.default"
        scope: request

    app.employee_manager:
        class: 'AppBundle\Manager\EmployeeManager'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@event_dispatcher"

    app.user_manager:
        class: 'AppBundle\Manager\UserManager'
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.team_manager:
        class: 'AppBundle\Manager\TeamManager'
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.vacation_request_manager:
        class: 'AppBundle\Manager\VacationRequestManager'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.holiday_manager:
        class: 'AppBundle\Manager\HolidayManager'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@translator.default"

    app.twig_extension:
        class: 'AppBundle\Twig\ProjectExtension'
        arguments:
            - "@doctrine.orm.entity_manager"
            - services:
                holiday: "@app.holiday_manager"
                vacation: "@app.vacation_request_manager"
                dispatcher: "@event_dispatcher"
        tags:
            - { name: twig.extension }

    app.dashboard_manager:
        class: 'AppBundle\Manager\DashboardManager'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - available:
                app.holiday_manager: "@app.holiday_manager"
                templating: "@templating"
                app.role_manager: "@app.role_manager"
                app.vacation_request_manager: "@app.vacation_request_manager"
                app.calendar_manager: "@app.calendar_manager"

    app.role_manager:
        class: 'AppBundle\Manager\RoleManager'
        arguments:
            - "@security.role_hierarchy"

    app.calendar_manager:
        class: 'AppBundle\Manager\CalendarManager'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.vacation_request_revival_manager:
        class: 'AppBundle\Manager\VacationRequestRevivalManager'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@event_dispatcher"

    #Application custom validators
    app.validator.date_range:
        class: 'AppBundle\Validator\Constraints\ConstraintsVacationDateValidator'
        tags:
            - { name: "validator.constraint_validator" }

    #Application's Event Listeners
    app.vacation_listener:
        class: 'AppBundle\Listener\VacationListener'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.mailer_manager"
        tags:
            - { name: "kernel.event_listener", event: "app.on_validate_event", method: "onValidate" }
            - { name: "kernel.event_listener", event: "app.on_submit_vacation_event", method: 'onSubmitRequest'}

    app.employee_listener:
            class: 'AppBundle\Listener\VacationEmployeeListener'
            arguments:
                - "@doctrine.orm.entity_manager"
            tags:
                - { name : "kernel.event_listener" , event: "app.on_user_process", method: "onCreateEmployee"}
                - { name : "kernel.event_listener" , event: "app.on_user_update", method: "onUpdateEmployee"}
                - { name : "kernel.event_listener" , event: "app.on_user_remove", method: "onRemoveEmployee"}

    app.revival_mail:
        class: 'AppBundle\Listener\RevivalMailListener'
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.mailer_manager"
        tags:
            - { name : "kernel.event_listener" , event: "app.revival_send_email", method: "onRevivalSendEmail"}
